spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.198.8:3306/midgard
    username: midgard
    password: y3fzkBMJQt3R62YE

logging:
  level:
    com.yggdrasil.labs.*: debug
    root: info

# 开发环境特定配置
# 例如：数据库连接、Redis 等

